server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testTask2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  messages:
    basename: validator